### ISSUE TITLE
3D Threshold Optimize Error

### ISSUE THREAD

**Issue by Jojo78987** [AhsenChaudhry/Mitochondria-Analyzer#12]
Even if I set the units of the pixel and voxel in Image-Properties the correct way, I was still informed that the units should be set correctlly. This didn't occur last year, but suddenly took place when I used the plugin two days ago.

Is there any approaches that I could try?

Many thanks for help.

**Comment by AhsenChaudhry** [comment]
I have updated the plugin now to hopefully resolve this by removing the pixel width value check. Should work now as long as the units are in "micron" or "microns", let me know if the error continues to persist.

**Comment by gerd-bizi** [comment]
It seems that it doesn't accept 'μm' as a unit. My images are from the LSM 710. Perhaps this should be added as well. I can modify the program to work correctly locally, but others might be having the same issue.

**Comment by AhsenChaudhry** [comment]
Thank you for the suggestion, I have updated it to accept 'μm' as a unit now.

**Comment by nathann12** [comment]
I am receiving the same error when using 'µm'. I attempted to use "micron" or "microns" as well to no avail. Any suggestions on what I should try? I just got this plugin today so there may be something I am missing.

**Comment by sygongcode** [comment]
Hi, 
It still not for me. Do I need to reinstall the new version? Thank you

**Comment by sygongcode** [comment]
> Hi, It still not for me. Do I need to reinstall the new version? Thank you
It still does not work for me. Fiji still suddenly closed. Sometimes, it works, sometimes not.

**Comment by gerd-bizi** [comment]
@sygongcode, it seems that the fix that Dr. Chaudry made didn't cover all bases.
I've written a quick .ijm script [here](https://github.com/gerd-bizi/gerd_bizi_bch374/blob/main/mito_analyzer_prep.ijm) that you could run to split your images into mito and other channels (I've hard-coded two channels in, but you could definitely change it to make it robust) with the proper units and as an 8-bit file. Let me know if this works!

**Comment by sygongcode** [comment]
> @sygongcode, it seems that the fix that Dr. Chaudry made didn't cover all bases. I've written a quick .ijm script [here](https://github.com/gerd-bizi/gerd_bizi_bch374/blob/main/mito_analyzer_prep.ijm) that you could run to split your images into mito and other channels (I've hard-coded two channels in, but you could definitely change it to make it robust) with the proper units and as an 8-bit file. Let me know if this works!

Hi, thank you for your reply. Unfortunity, it does not work. I download the script of your quick .ijm and copy to the folder of ~\Fiji.app\plugins\MitochondriaAnalyzer\Macros. And then I update Fiji. The error still exists. Do you knock if there are some other fuji plugins to analyze mitochondrial network? Thank you.

Best regard,
Shangyu

**Comment by gerd-bizi** [comment]
Hey Shangyu @sygongcode, the plug-in wasn't meant to be integrated directly into Mitochondria Analyzer, I'll add documentation to clarify that.
I ran the plug in outside of Mito Analyzer, and saved the split images to two separate directories.
Let me know if you have any further questions.

**Comment by sygongcode** [comment]
> Hey Shangyu @sygongcode, the plug-in wasn't meant to be integrated directly into Mitochondria Analyzer, I'll add documentation to clarify that. I ran the plug-in outside of Mito Analyzer and saved the split images to two separate directories. Let me know if you have any further questions.

Hi, Thank you for your help! I reinstalled the plugin following method 1 and changed the pixels to microns. And then resolve the problem.

**Comment by greeshma101** [comment]
I still have this issue @sygongcode can you share your document on how to install the plugin you wrote?
